// Code generated by protoc-gen-go. DO NOT EDIT.
// source: append_entries_call.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AppendEntriesCall struct {
	Term                 uint64      `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	LeaderId             string      `protobuf:"bytes,2,opt,name=LeaderId,proto3" json:"LeaderId,omitempty"`
	PrevLogIndex         uint64      `protobuf:"varint,3,opt,name=PrevLogIndex,proto3" json:"PrevLogIndex,omitempty"`
	PrevLogTerm          uint64      `protobuf:"varint,4,opt,name=PrevLogTerm,proto3" json:"PrevLogTerm,omitempty"`
	Entries              []*LogEntry `protobuf:"bytes,5,rep,name=Entries,proto3" json:"Entries,omitempty"`
	CommitIndex          uint64      `protobuf:"varint,6,opt,name=CommitIndex,proto3" json:"CommitIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AppendEntriesCall) Reset()         { *m = AppendEntriesCall{} }
func (m *AppendEntriesCall) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesCall) ProtoMessage()    {}
func (*AppendEntriesCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_8678a11708107e9f, []int{0}
}

func (m *AppendEntriesCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesCall.Unmarshal(m, b)
}
func (m *AppendEntriesCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesCall.Marshal(b, m, deterministic)
}
func (m *AppendEntriesCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesCall.Merge(m, src)
}
func (m *AppendEntriesCall) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesCall.Size(m)
}
func (m *AppendEntriesCall) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesCall.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesCall proto.InternalMessageInfo

func (m *AppendEntriesCall) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesCall) GetLeaderId() string {
	if m != nil {
		return m.LeaderId
	}
	return ""
}

func (m *AppendEntriesCall) GetPrevLogIndex() uint64 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntriesCall) GetPrevLogTerm() uint64 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntriesCall) GetEntries() []*LogEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *AppendEntriesCall) GetCommitIndex() uint64 {
	if m != nil {
		return m.CommitIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*AppendEntriesCall)(nil), "protobuf.AppendEntriesCall")
}

func init() { proto.RegisterFile("append_entries_call.proto", fileDescriptor_8678a11708107e9f) }

var fileDescriptor_8678a11708107e9f = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4c, 0x2c, 0x28, 0x48,
	0xcd, 0x4b, 0x89, 0x4f, 0xcd, 0x2b, 0x29, 0xca, 0x4c, 0x2d, 0x8e, 0x4f, 0x4e, 0xcc, 0xc9, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x52, 0xfc, 0x39, 0xf9,
	0xe9, 0x60, 0x15, 0x95, 0x10, 0x29, 0xa5, 0x9b, 0x8c, 0x5c, 0x82, 0x8e, 0x60, 0x8d, 0xae, 0x10,
	0x7d, 0xce, 0x89, 0x39, 0x39, 0x42, 0x42, 0x5c, 0x2c, 0x21, 0xa9, 0x45, 0xb9, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x2c, 0x41, 0x60, 0xb6, 0x90, 0x14, 0x17, 0x87, 0x4f, 0x6a, 0x62, 0x4a, 0x6a, 0x91,
	0x67, 0x8a, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x9c, 0x2f, 0xa4, 0xc4, 0xc5, 0x13, 0x50,
	0x94, 0x5a, 0xe6, 0x93, 0x9f, 0xee, 0x99, 0x97, 0x92, 0x5a, 0x21, 0xc1, 0x0c, 0xd6, 0x87, 0x22,
	0x26, 0xa4, 0xc0, 0xc5, 0x0d, 0xe5, 0x83, 0x8d, 0x66, 0x01, 0x2b, 0x41, 0x16, 0x12, 0xd2, 0xe1,
	0x62, 0x87, 0x3a, 0x42, 0x82, 0x55, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x48, 0x0f, 0xe6, 0x70, 0x3d,
	0x9f, 0xfc, 0x74, 0x90, 0x5c, 0x65, 0x10, 0x4c, 0x09, 0xc8, 0x3c, 0xe7, 0xfc, 0xdc, 0xdc, 0xcc,
	0x12, 0x88, 0x95, 0x6c, 0x10, 0xf3, 0x90, 0x84, 0x92, 0xd8, 0xc0, 0xba, 0x8d, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xa1, 0xbb, 0x57, 0xa5, 0x1a, 0x01, 0x00, 0x00,
}
