// Code generated by protoc-gen-go. DO NOT EDIT.
// source: append_entries.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AppendEntriesCall struct {
	// term of the leader
	Term uint64 `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	// if of the leader
	LeaderId string `protobuf:"bytes,2,opt,name=LeaderId,proto3" json:"LeaderId,omitempty"`
	// id of the last log entry before these `Entries`
	PrevLogIndex uint64 `protobuf:"varint,3,opt,name=PrevLogIndex,proto3" json:"PrevLogIndex,omitempty"`
	// term of the last log entry
	PrevLogTerm uint64 `protobuf:"varint,4,opt,name=PrevLogTerm,proto3" json:"PrevLogTerm,omitempty"`
	// the entries to be sent (empty for simple heartbeat)
	Entries []*AppendEntry `protobuf:"bytes,5,rep,name=Entries,proto3" json:"Entries,omitempty"`
	// index of the last commited log entry by the leader
	CommitIndex          uint64   `protobuf:"varint,6,opt,name=CommitIndex,proto3" json:"CommitIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntriesCall) Reset()         { *m = AppendEntriesCall{} }
func (m *AppendEntriesCall) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesCall) ProtoMessage()    {}
func (*AppendEntriesCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b4beeedbaf7b49a, []int{0}
}

func (m *AppendEntriesCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesCall.Unmarshal(m, b)
}
func (m *AppendEntriesCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesCall.Marshal(b, m, deterministic)
}
func (m *AppendEntriesCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesCall.Merge(m, src)
}
func (m *AppendEntriesCall) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesCall.Size(m)
}
func (m *AppendEntriesCall) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesCall.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesCall proto.InternalMessageInfo

func (m *AppendEntriesCall) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesCall) GetLeaderId() string {
	if m != nil {
		return m.LeaderId
	}
	return ""
}

func (m *AppendEntriesCall) GetPrevLogIndex() uint64 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntriesCall) GetPrevLogTerm() uint64 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntriesCall) GetEntries() []*AppendEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *AppendEntriesCall) GetCommitIndex() uint64 {
	if m != nil {
		return m.CommitIndex
	}
	return 0
}

type AppendEntriesRespond struct {
	// current term of the follower
	Term uint64 `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	// true if follower contained log entry with `PrevLogIndex` and `PrevLogTerm`
	Success              bool     `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntriesRespond) Reset()         { *m = AppendEntriesRespond{} }
func (m *AppendEntriesRespond) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesRespond) ProtoMessage()    {}
func (*AppendEntriesRespond) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b4beeedbaf7b49a, []int{1}
}

func (m *AppendEntriesRespond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesRespond.Unmarshal(m, b)
}
func (m *AppendEntriesRespond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesRespond.Marshal(b, m, deterministic)
}
func (m *AppendEntriesRespond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesRespond.Merge(m, src)
}
func (m *AppendEntriesRespond) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesRespond.Size(m)
}
func (m *AppendEntriesRespond) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesRespond.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesRespond proto.InternalMessageInfo

func (m *AppendEntriesRespond) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesRespond) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AppendEntry struct {
	// The content of the entry
	Content              []byte   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntry) Reset()         { *m = AppendEntry{} }
func (m *AppendEntry) String() string { return proto.CompactTextString(m) }
func (*AppendEntry) ProtoMessage()    {}
func (*AppendEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b4beeedbaf7b49a, []int{2}
}

func (m *AppendEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntry.Unmarshal(m, b)
}
func (m *AppendEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntry.Marshal(b, m, deterministic)
}
func (m *AppendEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntry.Merge(m, src)
}
func (m *AppendEntry) XXX_Size() int {
	return xxx_messageInfo_AppendEntry.Size(m)
}
func (m *AppendEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntry.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntry proto.InternalMessageInfo

func (m *AppendEntry) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*AppendEntriesCall)(nil), "protobuf.AppendEntriesCall")
	proto.RegisterType((*AppendEntriesRespond)(nil), "protobuf.AppendEntriesRespond")
	proto.RegisterType((*AppendEntry)(nil), "protobuf.AppendEntry")
}

func init() { proto.RegisterFile("append_entries.proto", fileDescriptor_5b4beeedbaf7b49a) }

var fileDescriptor_5b4beeedbaf7b49a = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x2c, 0x28, 0x48,
	0xcd, 0x4b, 0x89, 0x4f, 0xcd, 0x2b, 0x29, 0xca, 0x4c, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x4a, 0x77, 0x18, 0xb9, 0x04, 0x1d, 0xc1, 0x4a, 0x5c,
	0x21, 0x2a, 0x9c, 0x13, 0x73, 0x72, 0x84, 0x84, 0xb8, 0x58, 0x42, 0x52, 0x8b, 0x72, 0x25, 0x18,
	0x15, 0x18, 0x35, 0x58, 0x82, 0xc0, 0x6c, 0x21, 0x29, 0x2e, 0x0e, 0x9f, 0xd4, 0xc4, 0x94, 0xd4,
	0x22, 0xcf, 0x14, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x38, 0x5f, 0x48, 0x89, 0x8b, 0x27,
	0xa0, 0x28, 0xb5, 0xcc, 0x27, 0x3f, 0xdd, 0x33, 0x2f, 0x25, 0xb5, 0x42, 0x82, 0x19, 0xac, 0x0f,
	0x45, 0x4c, 0x48, 0x81, 0x8b, 0x1b, 0xca, 0x07, 0x1b, 0xcd, 0x02, 0x56, 0x82, 0x2c, 0x24, 0xa4,
	0xcf, 0xc5, 0x0e, 0x75, 0x84, 0x04, 0xab, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0xa8, 0x1e, 0xcc, 0x9d,
	0x7a, 0x08, 0x37, 0x56, 0x06, 0xc1, 0x54, 0x81, 0x8c, 0x74, 0xce, 0xcf, 0xcd, 0xcd, 0x2c, 0x81,
	0xd8, 0xca, 0x06, 0x31, 0x12, 0x49, 0x48, 0xc9, 0x85, 0x4b, 0x04, 0xc5, 0x77, 0x41, 0xa9, 0xc5,
	0x05, 0xf9, 0x79, 0x29, 0x58, 0x3d, 0x28, 0xc1, 0xc5, 0x1e, 0x5c, 0x9a, 0x9c, 0x9c, 0x5a, 0x5c,
	0x0c, 0xf6, 0x1f, 0x47, 0x10, 0x8c, 0xab, 0xa4, 0xce, 0xc5, 0x8d, 0x64, 0x3f, 0x48, 0x61, 0x72,
	0x7e, 0x5e, 0x49, 0x6a, 0x5e, 0x09, 0x58, 0x3f, 0x4f, 0x10, 0x8c, 0x9b, 0xc4, 0x06, 0x76, 0xaf,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xc8, 0xb8, 0xb0, 0xa7, 0x76, 0x01, 0x00, 0x00,
}
