// Code generated by protoc-gen-go. DO NOT EDIT.
// source: append_entries_respond.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AppendEntriesRespond struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntriesRespond) Reset()         { *m = AppendEntriesRespond{} }
func (m *AppendEntriesRespond) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesRespond) ProtoMessage()    {}
func (*AppendEntriesRespond) Descriptor() ([]byte, []int) {
	return fileDescriptor_be26f956247cc3c7, []int{0}
}

func (m *AppendEntriesRespond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesRespond.Unmarshal(m, b)
}
func (m *AppendEntriesRespond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesRespond.Marshal(b, m, deterministic)
}
func (m *AppendEntriesRespond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesRespond.Merge(m, src)
}
func (m *AppendEntriesRespond) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesRespond.Size(m)
}
func (m *AppendEntriesRespond) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesRespond.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesRespond proto.InternalMessageInfo

func (m *AppendEntriesRespond) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesRespond) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*AppendEntriesRespond)(nil), "protobuf.AppendEntriesRespond")
}

func init() { proto.RegisterFile("append_entries_respond.proto", fileDescriptor_be26f956247cc3c7) }

var fileDescriptor_be26f956247cc3c7 = []byte{
	// 115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x49, 0x2c, 0x28, 0x48,
	0xcd, 0x4b, 0x89, 0x4f, 0xcd, 0x2b, 0x29, 0xca, 0x4c, 0x2d, 0x8e, 0x2f, 0x4a, 0x2d, 0x2e, 0xc8,
	0xcf, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x4a,
	0x2e, 0x5c, 0x22, 0x8e, 0x60, 0x95, 0xae, 0x10, 0x85, 0x41, 0x10, 0x75, 0x42, 0x42, 0x5c, 0x2c,
	0x21, 0xa9, 0x45, 0xb9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0x60, 0xb6, 0x90, 0x04, 0x17,
	0x7b, 0x70, 0x69, 0x72, 0x72, 0x6a, 0x71, 0xb1, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x47, 0x10, 0x8c,
	0x9b, 0xc4, 0x06, 0x36, 0xcf, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x64, 0xe1, 0x00, 0xa0, 0x76,
	0x00, 0x00, 0x00,
}
