// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request_vote_call.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestVoteCall struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	CandidateId          uint64   `protobuf:"varint,2,opt,name=CandidateId,proto3" json:"CandidateId,omitempty"`
	LastLogIndex         uint64   `protobuf:"varint,3,opt,name=LastLogIndex,proto3" json:"LastLogIndex,omitempty"`
	LastLogTerm          uint64   `protobuf:"varint,4,opt,name=LastLogTerm,proto3" json:"LastLogTerm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteCall) Reset()         { *m = RequestVoteCall{} }
func (m *RequestVoteCall) String() string { return proto.CompactTextString(m) }
func (*RequestVoteCall) ProtoMessage()    {}
func (*RequestVoteCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_123c161765c2d40d, []int{0}
}

func (m *RequestVoteCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteCall.Unmarshal(m, b)
}
func (m *RequestVoteCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteCall.Marshal(b, m, deterministic)
}
func (m *RequestVoteCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteCall.Merge(m, src)
}
func (m *RequestVoteCall) XXX_Size() int {
	return xxx_messageInfo_RequestVoteCall.Size(m)
}
func (m *RequestVoteCall) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteCall.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteCall proto.InternalMessageInfo

func (m *RequestVoteCall) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteCall) GetCandidateId() uint64 {
	if m != nil {
		return m.CandidateId
	}
	return 0
}

func (m *RequestVoteCall) GetLastLogIndex() uint64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *RequestVoteCall) GetLastLogTerm() uint64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestVoteCall)(nil), "protobuf.RequestVoteCall")
}

func init() { proto.RegisterFile("request_vote_call.proto", fileDescriptor_123c161765c2d40d) }

var fileDescriptor_123c161765c2d40d = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0x89, 0x2f, 0xcb, 0x2f, 0x49, 0x8d, 0x4f, 0x4e, 0xcc, 0xc9, 0xd1, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x4a, 0xbd, 0x8c, 0x5c, 0xfc, 0x41,
	0x10, 0x55, 0x61, 0xf9, 0x25, 0xa9, 0xce, 0x89, 0x39, 0x39, 0x42, 0x42, 0x5c, 0x2c, 0x21, 0xa9,
	0x45, 0xb9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0x60, 0xb6, 0x90, 0x02, 0x17, 0xb7, 0x73,
	0x62, 0x5e, 0x4a, 0x66, 0x4a, 0x62, 0x49, 0xaa, 0x67, 0x8a, 0x04, 0x13, 0x58, 0x0a, 0x59, 0x48,
	0x48, 0x89, 0x8b, 0xc7, 0x27, 0xb1, 0xb8, 0xc4, 0x27, 0x3f, 0xdd, 0x33, 0x2f, 0x25, 0xb5, 0x42,
	0x82, 0x19, 0xac, 0x04, 0x45, 0x0c, 0x64, 0x0a, 0x94, 0x0f, 0xb6, 0x80, 0x05, 0x62, 0x0a, 0x92,
	0x50, 0x12, 0x1b, 0xd8, 0x65, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x58, 0xf5, 0x37, 0x30,
	0xbb, 0x00, 0x00, 0x00,
}
