// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request_vote_respond.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestVoteRespond struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	VoteGranted          bool     `protobuf:"varint,2,opt,name=VoteGranted,proto3" json:"VoteGranted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteRespond) Reset()         { *m = RequestVoteRespond{} }
func (m *RequestVoteRespond) String() string { return proto.CompactTextString(m) }
func (*RequestVoteRespond) ProtoMessage()    {}
func (*RequestVoteRespond) Descriptor() ([]byte, []int) {
	return fileDescriptor_a43172c07f14a774, []int{0}
}

func (m *RequestVoteRespond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteRespond.Unmarshal(m, b)
}
func (m *RequestVoteRespond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteRespond.Marshal(b, m, deterministic)
}
func (m *RequestVoteRespond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteRespond.Merge(m, src)
}
func (m *RequestVoteRespond) XXX_Size() int {
	return xxx_messageInfo_RequestVoteRespond.Size(m)
}
func (m *RequestVoteRespond) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteRespond.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteRespond proto.InternalMessageInfo

func (m *RequestVoteRespond) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteRespond) GetVoteGranted() bool {
	if m != nil {
		return m.VoteGranted
	}
	return false
}

func init() {
	proto.RegisterType((*RequestVoteRespond)(nil), "protobuf.RequestVoteRespond")
}

func init() { proto.RegisterFile("request_vote_respond.proto", fileDescriptor_a43172c07f14a774) }

var fileDescriptor_a43172c07f14a774 = []byte{
	// 117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0x89, 0x2f, 0xcb, 0x2f, 0x49, 0x8d, 0x2f, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x4b,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x4a, 0x5e, 0x5c,
	0x42, 0x41, 0x10, 0x75, 0x61, 0xf9, 0x25, 0xa9, 0x41, 0x10, 0x55, 0x42, 0x42, 0x5c, 0x2c, 0x21,
	0xa9, 0x45, 0xb9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0x60, 0xb6, 0x90, 0x02, 0x17, 0x37,
	0x48, 0x89, 0x7b, 0x51, 0x62, 0x5e, 0x49, 0x6a, 0x8a, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x47, 0x10,
	0xb2, 0x50, 0x12, 0x1b, 0xd8, 0x54, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd5, 0xe0, 0x58,
	0x14, 0x7a, 0x00, 0x00, 0x00,
}
